---
kind: ConfigMap
apiVersion: v1
metadata:
  name: tower-backend-cfg
  labels:
    app: backend-cfg
data:
  TOWER_ENABLE_UNSAFE_MODE: "true"
  TOWER_ROOT_USERS: "<root_users>"
  TOWER_SERVER_URL: "http://localhost:8080"
  TOWER_CONTACT_EMAIL: "user@example.com"
  TOWER_JWT_SECRET: "<jwt_secret>"
  TOWER_DB_URL: jdbc:mysql://mysql:3306/tower?permitMysqlScheme=true
  TOWER_DB_DRIVER: "org.mariadb.jdbc.Driver"
  TOWER_DB_USER: "tower"
  TOWER_DB_PASSWORD: "tower"
  TOWER_DB_DIALECT: "io.seqera.util.MySQL55DialectCollateBin"
  TOWER_DB_MIN_POOL_SIZE: "2"
  TOWER_DB_MAX_POOL_SIZE: "10"
  TOWER_DB_MAX_LIFETIME: "180000"
  TOWER_SMTP_HOST: "mailcatcher"
  TOWER_SMTP_USER: ""
  TOWER_SMTP_PASSWORD: ""
  TOWER_CRYPTO_SECRETKEY: "<crypt_secret>"
  TOWER_LICENSE: "<license>"
  TOWER_ENABLE_PLATFORMS: "local-platform"
  FLYWAY_LOCATIONS: "classpath:db-schema/mysql"
  TOWER_REDIS_URL: "redis://redis:6379"
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: tower-yml
  labels:
    app: backend-cfg
data:
  tower.yml: |
    mail:
      smtp:
        auth: false
        # FIXME `starttls` should be enabled with a production SMTP host
        starttls:
          enable: false
          required: false
        ssl:
          protocols: "TLSv1.2"

    auth:
      mail:
        duration: 30m

    # Set a custom application name for the Micronaut environment to deploy multiple instances from the same Enterprise account
    # Required for AWS Parameter Store configuration. For more information, see https://docs.seqera.io/platform/latest/enterprise/configuration/aws_parameter_store 
    micronaut:
      application:
        name: tower-app
