---
apiVersion: v1
kind: Pod
metadata:
  name: mailcatcher
  labels:
    app: mailcatcher
spec:
  containers:
  - name: mailcatcher
    image: sj26/mailcatcher
    ports:
    - containerPort: 1025
    - containerPort: 1080
---
apiVersion: v1
kind: Service
metadata:
  name: mailcatcher
spec:
  selector:
    app: mailcatcher
  ports:
  - name: smtp
    protocol: TCP
    port: 587
    targetPort: 1025
  - name: http
    protocol: TCP
    port: 1080
    targetPort: 1080
  type: ClusterIP
